# Generated by Django 6.1 on 2026-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_user_trackingevent_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
